# Generated by Django 5.1.6 on 2025-03-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255, unique=True)),
                ('car_model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['oname']},
        ),
    ]
