# Generated by Django 5.1.6 on 2025-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_product_car_model_alter_product_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='c_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='m_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
